### ISSUE TITLE
BTStatusTest example project fails to build for release on Android

### ISSUE THREAD

**Issue by damianfarina** [solinor/react-native-bluetooth-status#56]
After upgrading to 1.5.0 I started having issues to build an Android release APK. So, I tried the example project included in this repo and got the same failure:

```
➜  android git:(master) ./gradlew assembleRelease

> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
Loading dependency graph, done.
info Writing bundle output to:, /Users/damianfarina/react-native-bluetooth-status/examples/BTStatusTest/android/app/build/generated/assets/react/release/index.android.bundle
info Writing sourcemap output to:, /Users/damianfarina/react-native-bluetooth-status/examples/BTStatusTest/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map
info Done writing bundle output
info Done writing sourcemap output
info Copying 1 asset files
info Done copying assets

> Task :react-native-bluetooth-status:compileReleaseJavaWithJavac FAILED
/Users/damianfarina/react-native-bluetooth-status/examples/BTStatusTest/node_modules/react-native-bluetooth-status/android/src/main/java/com/solinor/bluetoothstatus/RNBluetoothManagerModule.java:9: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/damianfarina/react-native-bluetooth-status/examples/BTStatusTest/node_modules/react-native-bluetooth-status/android/src/main/java/com/solinor/bluetoothstatus/RNBluetoothManagerModule.java:36: error: cannot find symbol
                           @Nullable WritableMap params) {
                            ^
  symbol:   class Nullable
  location: class RNBluetoothManagerModule
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-bluetooth-status:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 44s
36 actionable tasks: 36 executed
```

It seems `RNBluetoothManagerModule.java` is importing an old Nullable package. Migrating it to AndroidX works as expected. The example project and my project build successfully if I change `RNBluetoothManagerModule.java` line 9 like this:
```
// import android.support.annotation.Nullable;
import androidx.annotation.Nullable;
```
